### ISSUE TITLE
Change post URL to be more industry-standard

### ISSUE THREAD

**Issue by zorbathut** [themotte/qcvault#20]
Example Reddit post URL: https://www.reddit.com/r/cats/comments/m1tgc2/cat_bonks_owner_for_attention/

Example QCVault post URL: https://localhost:44324/Post?title=How%20to%20take%20the%20headache%20out%20of%20catnip

What I'd like is:

https://localhost:44324/post/how_to_take_the_headache_out_of_catnip

The second part of the post can be derived entirely from the title; it's basically just tolower, strip non-alphanumeric-and-spaces, replace spaces with _. I don't know how the routing works but I assume there's some way to make it work.

**Comment by Akamitori** [comment]
Will look into how net core handles routing and see what we can do. Else, I will have to route the value in the format you want it to be then make sure to deformat it when inside the GET Request but then we will have to make sure the title never contains _.

**Comment by zorbathut** [comment]
There's definitely *some* way to do this, it's a pretty standard feature.

**Comment by zorbathut** [comment]
(not quite done, tinker with some of the formatting)
