### ISSUE TITLE
Do load testing.

### ISSUE THREAD

**Issue by zorbathut** [themotte/qcvault#30]

**Comment by Akamitori** [comment]
I assume you mean to try and load a bazzilion of posts? Or is it something else?

**Comment by zorbathut** [comment]
Yeah, you can find tools that will just hammer a website with tons of requests. See how many you can do and if it seems reasonable.

You may want to do this after https://github.com/themotte/qcvault/issues/29 - or, alternatively, do it before *and* after so you can see if it made a difference.

**Comment by zorbathut** [comment]
Currently it looks like this is around 100RPS, which is probably enough. I want to see if I can drop a caching proxy ahead of it to make it even faster.

**Comment by zorbathut** [comment]
4k rps or so, good 'nuff.
